[tox]
envlist=
  py{38,39,310}-django{40,41,42}

[testenv]
commands=python setup.py test

deps =
  django40: Django>=4.0, <4.1
  django41: Django>=4.1, <4.2
  django42: Django>=4.2, <5.0
  Pillow
  mock
